version: "3"

vars:
  PROJECT_NAME: number-trainer
  PYTHON_CMD: python3
  UV_CMD: uv

tasks:
  default:
    desc: "Показать доступные команды"
    cmds:
      - task --list

  # Установка и настройка
  install:
    desc: "Установить все зависимости проекта"
    cmds:
      - "{{.UV_CMD}} sync"
    sources:
      - pyproject.toml
    generates:
      - uv.lock

  install-dev:
    desc: "Установить зависимости для разработки"
    cmds:
      - "{{.UV_CMD}} sync --all-groups"
    sources:
      - pyproject.toml
    generates:
      - uv.lock

  # Запуск приложения
  run:
    desc: "Запустить GUI приложение"
    cmds:
      - "{{.UV_CMD}} run {{.PYTHON_CMD}} main.py"

  run-console:
    desc: "Запустить консольную версию тренажера"
    cmds:
      - "{{.UV_CMD}} run {{.PYTHON_CMD}} -m src.number_trainer.cli.console"

  run-web:
    desc: "Запустить веб-сервер (браузерная версия)"
    cmds:
      - "{{.UV_CMD}} run {{.PYTHON_CMD}} web_main.py"

  # Тестирование
  test:
    desc: "Запустить все тесты"
    deps: [install-dev]
    cmds:
      - "{{.UV_CMD}} run pytest tests/ -v"
    sources:
      - "src/**/*.py"
      - "tests/**/*.py"

  test-cov:
    desc: "Запустить тесты с покрытием кода"
    deps: [install-dev]
    cmds:
      - "{{.UV_CMD}} run pytest tests/ --cov=src/number_trainer --cov-report=term-missing --cov-report=html"
    sources:
      - "src/**/*.py"
      - "tests/**/*.py"
    generates:
      - htmlcov/

  test-watch:
    desc: "Запустить тесты в режиме наблюдения"
    deps: [install-dev]
    cmds:
      - "{{.UV_CMD}} run pytest tests/ -v --tb=short -x"
    watch: true
    sources:
      - "src/**/*.py"
      - "tests/**/*.py"

  # Качество кода
  lint:
    desc: "Проверить код линтерами"
    cmds:
      - task: ruff
      - task: mypy

  ruff:
    desc: "Проверить код ruff"
    deps: [install-dev]
    cmds:
      - "{{.UV_CMD}} run ruff check --fix src/ tests/ main.py web_main.py "

  mypy:
    desc: "Проверить код mypy"
    deps: [install-dev]
    cmds:
      - "{{.UV_CMD}} run mypy --package number_trainer --ignore-missing-imports"
      - "{{.UV_CMD}} run mypy main.py web_main.py --ignore-missing-imports"
  
  format:
    desc: "Отформатировать код"
    deps: [install-dev]
    cmds:
      - "{{.UV_CMD}} run ruff format src/ tests/ main.py web_main.py"
      - "{{.UV_CMD}} run ruff check --fix src/ tests/ main.py web_main.py"

  format-check:
    desc: "Проверить форматирование кода"
    deps: [install-dev]
    cmds:
      - "{{.UV_CMD}} run ruff format --check src/ tests/ main.py web_main.py"
      - "{{.UV_CMD}} run ruff check src/ tests/ main.py web_main.py"

  # CI/CD команды
  ci:
    desc: "Запустить все проверки как в CI"
    cmds:
      - task: format-check
      - task: lint
      - task: test-cov

  # Очистка
  clean:
    desc: "Очистить временные файлы"
    cmds:
      - rm -rf __pycache__
      - rm -rf .pytest_cache
      - rm -rf htmlcov
      - rm -rf .coverage
      - rm -rf *.pyc
      - rm -rf .mypy_cache
      - rm -rf .ruff_cache
      - rm -rf .task
      - rm -rf dist

  clean-all:
    desc: "Полная очистка включая виртуальное окружение"
    cmds:
      - task: clean
      - rm -rf .venv/
      - rm -f uv.lock

  # Сборка и развертывание
  build:
    desc: "Собрать проект"
    cmds:
      - "{{.UV_CMD}} build"
    sources:
      - "*.py"
      - pyproject.toml
    generates:
      - dist/

  # Docker commands
  docker-build:
    desc: "Собрать Docker образ"
    cmds:
      - docker build -t {{.PROJECT_NAME}}:latest .
    sources:
      - Dockerfile
      - pyproject.toml
      - "src/**/*.py"

  docker-run:
    desc: "Запустить Docker контейнер"
    cmds:
      - docker run -p 8000:8000 {{.PROJECT_NAME}}:latest

  docker-stop:
    desc: "Остановить все контейнеры приложения"
    cmds:
      - docker stop $$(docker ps -q --filter ancestor={{.PROJECT_NAME}}:latest) 2>/dev/null || true

  docker-clean:
    desc: "Очистить Docker образы и контейнеры"
    cmds:
      - docker stop $$(docker ps -q --filter ancestor={{.PROJECT_NAME}}:latest) 2>/dev/null || true
      - docker rm $$(docker ps -aq --filter ancestor={{.PROJECT_NAME}}:latest) 2>/dev/null || true
      - docker rmi {{.PROJECT_NAME}}:latest 2>/dev/null || true

  # GitHub Container Registry
  docker-build-ghcr:
    desc: "Собрать Docker образ для GitHub Container Registry"
    cmds:
      - docker build -t ghcr.io/{{.GITHUB_USERNAME}}/{{.PROJECT_NAME}}:latest .
      - docker tag ghcr.io/{{.GITHUB_USERNAME}}/{{.PROJECT_NAME}}:latest ghcr.io/{{.GITHUB_USERNAME}}/{{.PROJECT_NAME}}:{{.VERSION}}
    vars:
      GITHUB_USERNAME: '{{.GITHUB_USERNAME | default .PROJECT_NAME}}'
      VERSION: '{{.VERSION | default "latest"}}'
    sources:
      - Dockerfile
      - pyproject.toml
      - "src/**/*.py"

  docker-push-ghcr:
    desc: "Опубликовать Docker образ в GitHub Container Registry"
    cmds:
      - echo "Logging in to GitHub Container Registry..."
      - echo "{{.GITHUB_TOKEN}}" | docker login ghcr.io -u {{.GITHUB_USERNAME}} --password-stdin
      - docker push ghcr.io/{{.GITHUB_USERNAME}}/{{.PROJECT_NAME}}:latest
      - docker push ghcr.io/{{.GITHUB_USERNAME}}/{{.PROJECT_NAME}}:{{.VERSION}}
    vars:
      GITHUB_USERNAME: '{{.GITHUB_USERNAME | default .PROJECT_NAME}}'
      VERSION: '{{.VERSION | default "latest"}}'
    env:
      GITHUB_TOKEN: '{{.GITHUB_TOKEN}}'
    silent: true

  docker-publish:
    desc: "Собрать и опубликовать Docker образ в GitHub Container Registry"
    cmds:
      - task: docker-build-ghcr
      - task: docker-push-ghcr
    vars:
      GITHUB_USERNAME: '{{.GITHUB_USERNAME | default .PROJECT_NAME}}'
      VERSION: '{{.VERSION | default "latest"}}'

  # Docker Compose commands
  docker-compose-up:
    desc: "Запустить приложение через Docker Compose"
    cmds:
      - docker-compose up -d

  docker-compose-down:
    desc: "Остановить приложение через Docker Compose"
    cmds:
      - docker-compose down

  docker-compose-logs:
    desc: "Показать логи Docker Compose"
    cmds:
      - docker-compose logs -f

  docker-compose-build:
    desc: "Пересобрать образ через Docker Compose"
    cmds:
      - docker-compose build --no-cache

  # Production Docker commands
  docker-compose-prod:
    desc: "Запустить приложение в production режиме"
    cmds:
      - docker-compose -f docker-compose.prod.yml up -d

  docker-compose-prod-down:
    desc: "Остановить production приложение"
    cmds:
      - docker-compose -f docker-compose.prod.yml down

  docker-compose-prod-logs:
    desc: "Показать логи production приложения"
    cmds:
      - docker-compose -f docker-compose.prod.yml logs -f

  docker-compose-prod-build:
    desc: "Пересобрать production образ"
    cmds:
      - docker-compose -f docker-compose.prod.yml build --no-cache
