version: "3"

vars:
  PROJECT_NAME: number-trainer
  PYTHON_CMD: python3
  UV_CMD: uv

tasks:
  default:
    desc: "Show available commands"
    cmds:
      - task --list

  # Installation and setup
  install:
    desc: "Install all project dependencies"
    cmds:
      - "{{.UV_CMD}} sync"
    sources:
      - pyproject.toml
    generates:
      - uv.lock

  install-dev:
    desc: "Install development dependencies"
    cmds:
      - "{{.UV_CMD}} sync --all-groups"
    sources:
      - pyproject.toml
    generates:
      - uv.lock

  install-hooks:
    desc: "Install pre-commit hooks"
    deps: [install-dev]
    cmds:
      - "{{.UV_CMD}} run pre-commit install"

  # Application launch
  run:
    desc: "Launch GUI application"
    cmds:
      - "{{.UV_CMD}} run {{.PYTHON_CMD}} main.py"

  run-console:
    desc: "Launch console version of trainer"
    cmds:
      - "{{.UV_CMD}} run {{.PYTHON_CMD}} -m src.number_trainer.cli.console"

  run-web:
    desc: "Launch web server (browser version)"
    cmds:
      - "{{.UV_CMD}} run {{.PYTHON_CMD}} web_main.py"

  # Testing
  test:
    desc: "Run all tests"
    deps: [install-dev]
    cmds:
      - "{{.UV_CMD}} run pytest tests/ -v"
    sources:
      - "src/**/*.py"
      - "tests/**/*.py"

  test-cov:
    desc: "Run tests with code coverage"
    deps: [install-dev]
    cmds:
      - "{{.UV_CMD}} run pytest tests/ --cov=src/number_trainer --cov-report=term-missing --cov-report=html"
    sources:
      - "src/**/*.py"
      - "tests/**/*.py"
    generates:
      - htmlcov/

  test-watch:
    desc: "Run tests in watch mode"
    deps: [install-dev]
    cmds:
      - "{{.UV_CMD}} run pytest tests/ -v --tb=short -x"
    watch: true
    sources:
      - "src/**/*.py"
      - "tests/**/*.py"

  # Code quality
  lint:
    desc: "Check code with linters"
    cmds:
      - task: ruff
      - task: mypy

  ruff:
    desc: "Check code with ruff"
    deps: [install-dev]
    cmds:
      - "{{.UV_CMD}} run ruff check --fix src/ tests/ main.py web_main.py "

  mypy:
    desc: "Check code with mypy"
    deps: [install-dev]
    cmds:
      - "{{.UV_CMD}} run mypy --package number_trainer --ignore-missing-imports"
      - "{{.UV_CMD}} run mypy main.py web_main.py --ignore-missing-imports"

  format:
    desc: "Format code"
    deps: [install-dev]
    cmds:
      - "{{.UV_CMD}} run ruff format src/ tests/ main.py web_main.py"
      - "{{.UV_CMD}} run ruff check --fix src/ tests/ main.py web_main.py"

  format-check:
    desc: "Check code formatting"
    deps: [install-dev]
    cmds:
      - "{{.UV_CMD}} run ruff format --check src/ tests/ main.py web_main.py"
      - "{{.UV_CMD}} run ruff check src/ tests/ main.py web_main.py"

  # CI/CD commands
  ci:
    desc: "Run all checks as in CI"
    cmds:
      - task: format-check
      - task: lint
      - task: test-cov

  pre-commit:
    desc: "Run pre-commit on all files"
    deps: [install-dev]
    cmds:
      - "{{.UV_CMD}} run pre-commit run --all-files"

  # Cleanup
  clean:
    desc: "Clean temporary files"
    cmds:
      - rm -rf __pycache__
      - rm -rf .pytest_cache
      - rm -rf htmlcov
      - rm -rf .coverage
      - rm -rf *.pyc
      - rm -rf .mypy_cache
      - rm -rf .ruff_cache
      - rm -rf .task
      - rm -rf dist
      - rm -rf .pre-commit

  clean-all:
    desc: "Full cleanup including virtual environment"
    cmds:
      - task: clean
      - rm -rf .venv/
      - rm -f uv.lock

  # Build and deployment
  build:
    desc: "Build project"
    cmds:
      - "{{.UV_CMD}} build"
    sources:
      - "*.py"
      - pyproject.toml
    generates:
      - dist/

  # Docker commands
  docker-build:
    desc: "Build Docker image"
    cmds:
      - docker build -t {{.PROJECT_NAME}}:latest .
    sources:
      - Dockerfile
      - pyproject.toml
      - "src/**/*.py"

  docker-run:
    desc: "Run Docker container"
    cmds:
      - docker run -p 8000:8000 {{.PROJECT_NAME}}:latest

  docker-stop:
    desc: "Stop all application containers"
    cmds:
      - docker stop $$(docker ps -q --filter ancestor={{.PROJECT_NAME}}:latest) 2>/dev/null || true

  docker-clean:
    desc: "Clean Docker images and containers"
    cmds:
      - docker stop $$(docker ps -q --filter ancestor={{.PROJECT_NAME}}:latest) 2>/dev/null || true
      - docker rm $$(docker ps -aq --filter ancestor={{.PROJECT_NAME}}:latest) 2>/dev/null || true
      - docker rmi {{.PROJECT_NAME}}:latest 2>/dev/null || true

  # GitHub Container Registry
  docker-build-ghcr:
    desc: "Build Docker image for GitHub Container Registry"
    cmds:
      - docker build -t ghcr.io/{{.GITHUB_USERNAME}}/{{.PROJECT_NAME}}:latest .
      - docker tag ghcr.io/{{.GITHUB_USERNAME}}/{{.PROJECT_NAME}}:latest ghcr.io/{{.GITHUB_USERNAME}}/{{.PROJECT_NAME}}:{{.VERSION}}
    vars:
      GITHUB_USERNAME: '{{.GITHUB_USERNAME | default .PROJECT_NAME}}'
      VERSION: '{{.VERSION | default "latest"}}'
    sources:
      - Dockerfile
      - pyproject.toml
      - "src/**/*.py"

  docker-push-ghcr:
    desc: "Publish Docker image to GitHub Container Registry"
    cmds:
      - echo "Logging in to GitHub Container Registry..."
      - echo "{{.GITHUB_TOKEN}}" | docker login ghcr.io -u {{.GITHUB_USERNAME}} --password-stdin
      - docker push ghcr.io/{{.GITHUB_USERNAME}}/{{.PROJECT_NAME}}:latest
      - docker push ghcr.io/{{.GITHUB_USERNAME}}/{{.PROJECT_NAME}}:{{.VERSION}}
    vars:
      GITHUB_USERNAME: '{{.GITHUB_USERNAME | default .PROJECT_NAME}}'
      VERSION: '{{.VERSION | default "latest"}}'
    env:
      GITHUB_TOKEN: '{{.GITHUB_TOKEN}}'
    silent: true

  docker-publish:
    desc: "Build and publish Docker image to GitHub Container Registry"
    cmds:
      - task: docker-build-ghcr
      - task: docker-push-ghcr
    vars:
      GITHUB_USERNAME: '{{.GITHUB_USERNAME | default .PROJECT_NAME}}'
      VERSION: '{{.VERSION | default "latest"}}'

  # Docker Compose commands
  docker-compose-up:
    desc: "Launch application via Docker Compose"
    cmds:
      - docker-compose up -d

  docker-compose-down:
    desc: "Stop application via Docker Compose"
    cmds:
      - docker-compose down

  docker-compose-logs:
    desc: "Show Docker Compose logs"
    cmds:
      - docker-compose logs -f

  docker-compose-build:
    desc: "Rebuild image via Docker Compose"
    cmds:
      - docker-compose build --no-cache

  # Production Docker commands
  docker-compose-prod:
    desc: "Launch application in production mode"
    cmds:
      - docker-compose -f docker-compose.prod.yml up -d

  docker-compose-prod-down:
    desc: "Stop production application"
    cmds:
      - docker-compose -f docker-compose.prod.yml down

  docker-compose-prod-logs:
    desc: "Show production application logs"
    cmds:
      - docker-compose -f docker-compose.prod.yml logs -f

  docker-compose-prod-build:
    desc: "Rebuild production image"
    cmds:
      - docker-compose -f docker-compose.prod.yml build --no-cache
