name: Build Docker Image (Test Only)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Get version from pyproject.toml
      id: version
      run: |
        VERSION=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['version'])")
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Using version: $VERSION"

    - name: Build Docker image (test only)
      id: build
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: number-trainer:test
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test the image
      run: |
        echo "Starting container for testing..."
        docker run --rm -d -p 8000:8000 --name test-app number-trainer:test
        
        echo "Waiting for application to start..."
        sleep 10
        
        echo "Testing health endpoint..."
        curl -f http://localhost:8000/api/health || {
          echo "Health check failed!"
          docker logs test-app
          exit 1
        }
        
        echo "Health check passed! Stopping container..."
        docker stop test-app
        echo "Test completed successfully!"
